apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: node-express
  namespace: fbdev
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: node-express
    apps.tanzu.vmware.com/has-tests: true
  annotations: 
    autoscaling.knative.dev/minScale: 1
spec:
  source:
    git:
      ref:
        branch: main
      url: https://github.com/fabianbrash/fabianbrash-node-express-tap.git
